M48
; DRILL file {KiCad 8.0.6} date 2024-11-13T15:41:55-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-13T15:41:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X121.61Y-68.0
X127.39Y-68.0
T2
X103.5Y-146.525
X103.6Y-66.6
X143.4Y-66.6
X143.4Y-146.2
M30
