M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu22.04.1} date 2025-09-21T20:46:35-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-21T20:46:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X120.61Y-68.0
X126.39Y-68.0
T2
X103.5Y-146.525
X103.6Y-66.6
X143.4Y-66.6
X143.4Y-146.2
M30
